 # NumPy Tutorial

 This should give you a grasp on NumPy’s essential operations, including **fancy indexing** and **boolean masking**.

 ## 1. Installation and Import



 1. **Install NumPy** (if you haven’t already):


In [ ]:
# Install numpy using pip
!pip install numpy

This downloads and installs the NumPy package from the Python Package Index (PyPI).
The `as np` alias is a common convention that makes it easier to reference NumPy throughout your code.


In [1]:
# Importing NumPy
import numpy as np

 ## 2. Creating Arrays



 NumPy arrays are the core data structure for fast numerical computation in Python. They’re more efficient than standard Python lists for large-scale numerical operations.

In [2]:
# From Python Lists
arr_list = [1, 2, 3, 4]
arr_np = np.array(arr_list)
print(arr_np)       # [1 2 3 4]
print(arr_np.dtype) # e.g., int64


[1 2 3 4]
int32


In [3]:
# Using Built-in Functions
zeros_arr = np.zeros((2, 3))       # 2x3 array of zeros
ones_arr = np.ones(5)              # 1D array of ones
range_arr = np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]
lin_arr = np.linspace(0, 1, 5)     # [0., 0.25, 0.5, 0.75, 1.]

print(zeros_arr)
print(ones_arr)
print(range_arr)
print(lin_arr)


[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


 ## 3. Basic Operations



 NumPy arrays allow you to perform **element-wise** arithmetic with concise syntax, which is much faster than using regular Python lists in a loop.

In [4]:
# Arithmetic
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)       # [11 22 33]
print(x * 2)       # [2 4 6]
print(x * y)       # [10 40 90]


[11 22 33]
[2 4 6]
[10 40 90]


In [5]:
# Array Statistics
arr = np.array([1, 2, 3, 4, 5])
print(arr.mean())  # 3.0
print(arr.sum())   # 15
print(arr.max())   # 5


3.0
15
5


 ## 4. Reshaping and Indexing

In [6]:
# Reshape
mat = np.arange(1, 7)   # [1 2 3 4 5 6]
mat_2d = mat.reshape(2, 3)
print(mat_2d)


[[1 2 3]
 [4 5 6]]


In [7]:
# Slicing
# 1D slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:3])       # [20 30]

# 2D slicing
mat_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(mat_2d[0, 1])   # 2  (row 0, col 1)
print(mat_2d[:, 0])   # [1 4] (all rows, col 0)


[20 30]
2
[1 4]


 ## 5. Fancy Indexing and Boolean Masking

In [8]:
# Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
idx = np.array([2, 0, 3])  # positions to pick
print(arr[idx])            # [30 10 40]


[30 10 40]


In [9]:
# Boolean Masking
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(mask)        # [False False  True  True  True]
print(arr[mask])   # [30 40 50]


[False False  True  True  True]
[30 40 50]


 ## 6. Broadcasting

In [10]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


 ## 7. Random and Useful Utilities

In [17]:
# Random numbers
rand_arr = np.random.rand(3, 2)    # uniform in [0,1)
randn_arr = np.random.randn(3, 2)  # normal distribution (mean=0, std=1)

# Inspect shape
print('rand_arr:\n',rand_arr)
print(rand_arr.shape)  # (3, 2)

print('randn_arr:\n',randn_arr)

rand_arr:
 [[0.7397234  0.42995781]
 [0.83363984 0.86023017]
 [0.29664959 0.75299743]]
(3, 2)
randn_arr:
 [[-0.15344301  0.42799947]
 [ 1.22769764  1.25271484]
 [ 0.91410398 -0.50584797]]


 ## 8. Conclusion and Next Steps



 1. **Array Creation & Reshaping**: Master these to handle initial data processing.

 2. **Indexing & Slicing**: Use these techniques to quickly extract or modify parts of your dataset.

 3. **Fancy Indexing & Boolean Masking**: Powerful shortcuts for rearranging or filtering data based on conditions.

 4. **Broadcasting**: Simplifies arithmetic with mismatched shapes.

 5. **Random Utilities**: Ideal for simulations, data augmentation, or test scenarios.

 # Questions



 Solve the following exercises to practice NumPy basics. Follow the instructions and fill in the blanks where indicated.

 There is no need to submit this notebook; it's for your practice only.

 ## 1. Array Creation and Initialization



 **Task:**

 1. Create a 1D NumPy array of the first 10 positive integers.

 2. Create a 2x5 array of zeros.

 3. Create a 4x4 identity matrix.

In [24]:
# Your solution:
# 1. Create a 1D NumPy array of the first 10 positive integers
first_ten_pos_int = np.arange(1,11,1)
print(first_ten_pos_int,'\n')

# 2. Create a 2x5 array of zeros
arr_zeros = np.zeros((2,5))
print(arr_zeros,'\n')

# 3. Create a 4x4 identity matrix
arr_identity = np.identity(4, dtype=int)
print(arr_identity,'\n')


[ 1  2  3  4  5  6  7  8  9 10] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 



 ## 2. Array Operations



 **Task:**

 Given the array `arr = np.array([5, 10, 15, 20, 25])`, do the following:

 1. Multiply each element by 3.

 2. Subtract 5 from each element.

 3. Compute the sum of all elements in the resulting array.

In [26]:
# Your solution:
arr = np.array([5, 10, 15, 20, 25])
print(arr,"\n")

# 1. Multiply each element by 3
arr = arr * 3
print(arr,"\n")

# 2. Subtract 5 from each element
arr = arr - 5
print(arr,"\n")

# 3. Compute the sum of all elements
arr_sum = arr.sum()
print(arr_sum,"\n")

[ 5 10 15 20 25] 

[15 30 45 60 75] 

[10 25 40 55 70] 

200 



 ## 3. Reshaping and Indexing



 **Task:**

 1. Create a 1D array of integers from 1 to 12.

 2. Reshape it into a 3x4 matrix.

 3. Extract the element in the 2nd row, 3rd column.

 4. Extract the first column as a 1D array.

In [32]:
# Your solution:

# 1. Create a 1D array of integers from 1 to 12
arr_1d_int = np.arange(1,13,dtype=int)
print(arr_1d_int, "\n")

# 2. Reshape it into a 3x4 matrix
reshape_arr = arr_1d_int.reshape((3,4))
print(reshape_arr, "\n")

# 3. Extract the element in the 2nd row, 3rd column
print(reshape_arr[1,2],"\n")

# 4. Extract the first column as a 1D array
print(reshape_arr[:,0])

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

7 

[1 5 9]


 ## 4. Fancy Indexing



 **Task:**

 Given `arr = np.array([100, 200, 300, 400, 500])` and `indices = np.array([4, 0, 2])`:

 1. Use fancy indexing to extract the elements at positions defined by `indices`.

 2. Rearrange the extracted elements into descending order.

In [41]:
# Your solution:
arr = np.array([100, 200, 300, 400, 500])
indices = np.array([4, 0, 2])

# 1. Use fancy indexing to extract elements
arr_indices = arr[indices]
print(arr_indices,"\n")

# 2. Rearrange the extracted elements into descending order
arr_indices_asc = np.sort(arr_indices)
print("Ascending:",arr_indices_asc,"\n")
print("Descending:",arr_indices_asc[::-1])

[500 100 300] 

Ascending: [100 300 500] 

Descending: [500 300 100]


 ## 5. Boolean Masking



 **Task:**

 Given `arr = np.array([1, 4, 7, 10, 13, 16])`:

 1. Create a boolean mask for elements greater than 8.

 2. Use the mask to extract those elements.

 3. Compute the mean of the extracted elements.

In [47]:
# Your solution:
arr = np.array([1, 4, 7, 10, 13, 16])
print(arr,"\n")

# 1. Create a boolean mask for elements greater than 8
arr_greater = arr > 8
print("Greater than 8:",arr_greater,"\n")

# 2. Use the mask to extract those elements
arr_elements = arr[arr_greater==True]
print("Selection:",arr_elements)

# 3. Compute the mean of the extracted elements
print("Mean:",arr_elements.mean())


[ 1  4  7 10 13 16] 

Greater than 8: [False False False  True  True  True] 

Selection: [10 13 16]
Mean: 13.0


 ## 6. Broadcasting



 **Task:**

 Given the 2D array `a = np.array([[1, 2, 3], [4, 5, 6]])`:

 1. Add the 1D array `b = np.array([10, 20, 30])` to each row of `a`.

 2. Multiply each element of `a` by 2.

 3. Compute the sum of all elements in the resulting array.

In [51]:
# Your solution:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# 1. Add `b` to each row of `a`
a = a + b
print(a,"\n")

# 2. Multiply each element of `a` by 2
a = a * 2
print(a,"\n")

# 3. Compute the sum of all elements
print(a.sum())

[[11 22 33]
 [14 25 36]] 

[[22 44 66]
 [28 50 72]] 

282


 ## 7. Random Array Utilities



 **Task:**

 1. Generate a 3x3 array of random values uniformly distributed between 0 and 1.

 2. Generate a 3x3 array of random values drawn from a standard normal distribution.

 3. Compute the mean and standard deviation of each array.

In [65]:
# Your solution:

# 1. Generate a 3x3 array of random values uniformly distributed between 0 and 1
rand_arr_uniform = np.random.rand(3,3)
print(rand_arr_uniform,"\n")

# 2. Generate a 3x3 array of random values drawn from a standard normal distribution
rand_normal_arr = np.random.randn(3,3)
print(rand_normal_arr, '\n')

# 3. Compute the mean and standard deviation of each array

print('Item------------','Mean','Stdev')
print('rand_arr_uniform', f"{rand_arr_uniform.mean():.2f}", f"{rand_arr_uniform.std():.2f}")
print('rand_normal_arr ', f"{rand_normal_arr.mean():.2f}", f"{rand_normal_arr.std():.2f}")


[[0.32074624 0.15478792 0.51256252]
 [0.13672701 0.53844302 0.81610593]
 [0.73282123 0.54739823 0.49260673]] 

[[ 0.87788971  1.03594723 -1.25778977]
 [ 0.92640722  1.17875685 -2.27212001]
 [ 0.79370903  0.28796011  0.76043333]] 

Item------------ Mean Stdev
rand_arr_uniform 0.47 0.22
rand_normal_arr  0.26 1.13
